
services:
  etl:
    build: ./01_etl
    image: etl
    volumes:
      - etl_log:/app/logs
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ES_HOST=elastic
      - ES_PORT=${ES_PORT}
    depends_on:
      - postgres
      - elastic


  postgres:
    build: ./db
    image: psql
    expose:
      - ${DB_PORT}
    ports:
      - "127.0.0.1:5432:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data/


  elastic:
    image: elasticsearch:7.17.0
    expose:
      - ${ES_PORT}
    ports:
      - "127.0.0.1:1234:${ES_PORT}"
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - "discovery.type=single-node"

volumes:
  web-static:
  pgdata:
  etl_log:

